// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDiEpB3D4ho3IRWZEXSQkjB9I63b9QZ6Q',
    appId: '1:84910235253:web:f56c0f3f027dd60f80a23c',
    messagingSenderId: '84910235253',
    projectId: 'black-cirrus-323706',
    authDomain: 'black-cirrus-323706.firebaseapp.com',
    storageBucket: 'black-cirrus-323706.appspot.com',
    measurementId: 'G-318JZ5CVC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSPRZigQVAK7PfIl8LM-LN81TvDPJzxI',
    appId: '1:84910235253:android:1db260b20781c73180a23c',
    messagingSenderId: '84910235253',
    projectId: 'black-cirrus-323706',
    storageBucket: 'black-cirrus-323706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPwHhviD3Vuc8IJq-9BJ1K3zCSm_CQEBA',
    appId: '1:84910235253:ios:28c67fe1e4184a4480a23c',
    messagingSenderId: '84910235253',
    projectId: 'black-cirrus-323706',
    storageBucket: 'black-cirrus-323706.appspot.com',
    iosClientId: '84910235253-bu1ghlaoabsb0rpb9ni6qv1gt2vn0j2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPwHhviD3Vuc8IJq-9BJ1K3zCSm_CQEBA',
    appId: '1:84910235253:ios:28c67fe1e4184a4480a23c',
    messagingSenderId: '84910235253',
    projectId: 'black-cirrus-323706',
    storageBucket: 'black-cirrus-323706.appspot.com',
    iosClientId: '84910235253-bu1ghlaoabsb0rpb9ni6qv1gt2vn0j2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterWebsite',
  );
}
